---

- name: Registering known hosts
  known_hosts:
    name: "{{ item.name if item.name is defined else item }}"
    path: "/etc/ssh/ssh_known_hosts"
    state: present
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa {{ item }}') }}"
  with_items:
    - "{{ ssh_known_hosts }}"
